application: faster-nrj-hrd
version: 2-3
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "30d"

libraries:
  - name: django
    version: "1.2"

handlers:
  - url: /static
    static_dir: static

  - url: /devis
    script: redirect.application

  - url: /(.*)
    script: main.application
